-- MySQL Script generated by MySQL Workbench
-- Wed Jul 13 17:37:24 2022
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema analytics
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema analytics
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `analytics` DEFAULT CHARACTER SET utf8 ;
USE `analytics` ;

-- -----------------------------------------------------
-- Table `analytics`.`messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `analytics`.`messages` (
  `name` VARCHAR(500) NULL,
  `type` VARCHAR(500) NULL,
  `id` VARCHAR(500) NOT NULL,
  `datetime` datetime NOT NULL,
  `timestamp` TIMESTAMP NULL,
  `elapsedTime` varchar(500) NULL,
  `message` TEXT NULL,
  `amountValue` FLOAT NULL,
  `amountString` VARCHAR(500) NULL,
  `channelId` VARCHAR(500) NULL,
  `channelUrl`  VARCHAR(500) NULL,
  `bgColor` BIGINT NULL,
  `currency` VARCHAR(500) NULL,
  `topic` VARCHAR(45) NULL,
  `badgeUrl` VARCHAR(500) NULL,
  `imageUrl`  VARCHAR(500) NULL,
  `isChatModerator` BOOLEAN NULL,
  `isChatOwner` BOOLEAN NULL,
  `isChatSponsor` BOOLEAN NULL,
  `isVerified` BOOLEAN NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
